DEFAULT_NAME1: str = "Player 1"
DEFAULT_NAME2: str = "Player 2"

DEFAULT_SYMBOL1: str = "X"
DEFAULT_SYMBOL2: str = "O"
DEFAULT_SYMBOL_EMPTY: str = "_"

MSG_NAME: str = "{} , please enter your name\n"
MSG_NAME_CONF: str = "Your name has been assigned {}"
MSG_NAME_FORB: str = "{} is invalid name"

MSG_SYMBOL: str = "{}, please enter your 1 length symbol\n"
MG_SYMBOL_CONf: str = "{} has been assigned {}"
MG_SYMBOL_FORB: str = "{} is an invalid symbol "

MSG_MAKE_MOVE: str = "{} enter row number,column number seperated by comma.Row,col start with 1.\n"

MSG_OCCUPIED_SQUARE: str = "This square is already occupied, please try another square"
MSG_INVALID_MOVE: str = "invalid move, please try again"
BOARD_ATLEAST_3 = "board must have atleast 3 length"
BOARD_NOT_SQUARE = "board is not a sqaure array"
BOARD_INVALID_DIM = "board is not 2 dimensional"
RESULT = "Result is {}"
GAME_FINISHED = "This game is already over. Current status is {}"
CORD_OUT_BOUND = "Coordinates out of board"
CORD_NOT_INT = "Please enter integers as coordinates"
MOVE_NOT_2_CORD = "Please enter 2 coordinates"
SYB_NOT_ALLOW = "Symbol is not allowed: {}"
SYM_NOT_SIZE_1 = "Symbol is not of size1 : {}"
MSG_UNIQ_NAMES = " 2 names must be distinct"
MSG_UNIQ_SYB = "the 3 symbols must be distinct"
MSG_MIN_BD_SIZE = "board must be of atleast 3 size"
SEPERATION_SYM = ' '
INVAL_POSITION = "INVALID NUMBER OF MOVES FOR PLAYERS"
INVALID_BRD_SYM = "Board has Invalid Symbols"
